# Generated by Django 4.1.7 on 2023-04-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tesis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='happiness_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
    ]
