# Generated by Django 4.2.5 on 2023-10-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tesis', '0005_alter_person_agr1_alter_person_agr10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_location',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_location_city',
            field=models.CharField(blank=True, default='Ciudad', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_location_country',
            field=models.CharField(blank=True, default='Pais', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_location_province',
            field=models.CharField(blank=True, default='Provincia', max_length=100, null=True),
        ),
    ]
