# Generated by Django 4.2.5 on 2023-10-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tesis', '0006_remove_person_birth_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='submission_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
