from django.db import models
    
class Person(models.Model):
    birth_date = models.DateField(default='1900-01-01', null=True, blank=True)
    birth_hour = models.TimeField(default='00:00:00', null=True, blank=True)
    birth_location_city = models.CharField(max_length=100, default='Ciudad', null=True, blank=True)
    birth_location_province = models.CharField(max_length=100, default='Provincia', null=True, blank=True)
    birth_location_country = models.CharField(max_length=100, default='Pais', null=True, blank=True)
    degree = models.CharField(max_length=100, default='None', null=True, blank=True)
    happiness_level = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    submission_datetime = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    ext1 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    ext2 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    ext3 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    ext4 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    ext5 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    ext6 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    ext7 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    ext8 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    ext9 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    ext10 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    est1 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    est2 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    est3 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    est4 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    est5 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    est6 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    est7 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    est8 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    est9 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    est10 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    agr1 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    agr2 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    agr3 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    agr4 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    agr5 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    agr6 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    agr7 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    agr8 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    agr9 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    agr10 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    csn1 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    csn2 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    csn3 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    csn4 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    csn5 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    csn6 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    csn7 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    csn8 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    csn9 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    csn10 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    opn1 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    opn2 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    opn3 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    opn4 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    opn5 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    opn6 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    opn7 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    opn8 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    opn9 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)
    opn10 = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1, null=True, blank=True)